<a href="https://colab.research.google.com/github/atulnath/Pandas-100-days-challenge/blob/main/pandas_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
data = {
    'name':['Atul', 'Rahim', 'Ali', 'Dahnush', 'Rahman'],
    'age': [25,29,27,31,20],
    'city': ['Dhaka', 'Berlin', 'Chiitagong', 'Munich','Dresden']
}

df = pd.DataFrame(data)
df

name  age        city
0     Atul   25       Dhaka
1    Rahim   29      Berlin
2      Ali   27  Chiitagong
3  Dahnush   31      Munich
4   Rahman   20     Dresden

In [3]:
print('Dataframes: \n', df)

Dataframes: 
       name  age        city
0     Atul   25       Dhaka
1    Rahim   29      Berlin
2      Ali   27  Chiitagong
3  Dahnush   31      Munich
4   Rahman   20     Dresden


In [4]:
# Lets see our data

print('First 2 row: \n', df.head(2))

First 2 row: 
     name  age    city
0   Atul   25   Dhaka
1  Rahim   29  Berlin


In [5]:
# Lets see our data

print('last 2 row: \n', df.tail(2))

last 2 row: 
       name  age     city
3  Dahnush   31   Munich
4   Rahman   20  Dresden


In [6]:
# Column names

print('Column names: \n', df.columns)

Column names: 
 Index(['name', 'age', 'city'], dtype='object')


In [7]:
# info about our data

print('Info about our data: \n', df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   age     5 non-null      int64 
 2   city    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
Info about our data: 
 None


In [8]:
df.describe() # For the age or numberic value (Statistics)

age
count   5.000000
mean   26.400000
std     4.219005
min    20.000000
25%    25.000000
50%    27.000000
75%    29.000000
max    31.000000

In [9]:
df['name'] # Seeing out colums

0       Atul
1      Rahim
2        Ali
3    Dahnush
4     Rahman
Name: name, dtype: object

In [10]:
df.iloc[0] # showing values in loc 1

name     Atul
age        25
city    Dhaka
Name: 0, dtype: object

In [11]:
df[df['age'] > 27] # Filtering

name  age    city
1    Rahim   29  Berlin
3  Dahnush   31  Munich

In [12]:
# Changing the data

df['age'] = df['age'] + 2

df

name  age        city
0     Atul   27       Dhaka
1    Rahim   31      Berlin
2      Ali   29  Chiitagong
3  Dahnush   33      Munich
4   Rahman   22     Dresden

In [13]:
df.loc[df['age'] > 30, 'city'] = 'Dhaka'

In [14]:
df

name  age        city
0     Atul   27       Dhaka
1    Rahim   31       Dhaka
2      Ali   29  Chiitagong
3  Dahnush   33       Dhaka
4   Rahman   22     Dresden

In [15]:
# Add new columns

df['country'] = ['Bangladesh', 'India', 'Pakistan', 'Nepal', 'USA']

In [16]:
df

name  age        city     country
0     Atul   27       Dhaka  Bangladesh
1    Rahim   31       Dhaka       India
2      Ali   29  Chiitagong    Pakistan
3  Dahnush   33       Dhaka       Nepal
4   Rahman   22     Dresden         USA

In [17]:
df.sort_values(by='age', ascending=False)

name  age        city     country
3  Dahnush   33       Dhaka       Nepal
1    Rahim   31       Dhaka       India
2      Ali   29  Chiitagong    Pakistan
0     Atul   27       Dhaka  Bangladesh
4   Rahman   22     Dresden         USA

In [18]:
df.sort_values(by='country', ascending=True)

name  age        city     country
0     Atul   27       Dhaka  Bangladesh
1    Rahim   31       Dhaka       India
3  Dahnush   33       Dhaka       Nepal
2      Ali   29  Chiitagong    Pakistan
4   Rahman   22     Dresden         USA

In [19]:
df

name  age        city     country
0     Atul   27       Dhaka  Bangladesh
1    Rahim   31       Dhaka       India
2      Ali   29  Chiitagong    Pakistan
3  Dahnush   33       Dhaka       Nepal
4   Rahman   22     Dresden         USA

In [20]:
df.groupby('country')['age'].mean()

country
Bangladesh    27.0
India         31.0
Nepal         33.0
Pakistan      29.0
USA           22.0
Name: age, dtype: float64

In [21]:
df.groupby('city')['age'].mean()

city
Chiitagong    29.000000
Dhaka         30.333333
Dresden       22.000000
Name: age, dtype: float64

In [22]:
# Missing data handling

df.loc[1,'city'] = np.nan

df

name  age        city     country
0     Atul   27       Dhaka  Bangladesh
1    Rahim   31         NaN       India
2      Ali   29  Chiitagong    Pakistan
3  Dahnush   33       Dhaka       Nepal
4   Rahman   22     Dresden         USA

In [23]:
df.loc[1,'city'] = 'Berlin'

In [24]:
df

name  age        city     country
0     Atul   27       Dhaka  Bangladesh
1    Rahim   31      Berlin       India
2      Ali   29  Chiitagong    Pakistan
3  Dahnush   33       Dhaka       Nepal
4   Rahman   22     Dresden         USA

In [25]:
df.loc[1,'age'] = np.nan
df

name   age        city     country
0     Atul  27.0       Dhaka  Bangladesh
1    Rahim   NaN      Berlin       India
2      Ali  29.0  Chiitagong    Pakistan
3  Dahnush  33.0       Dhaka       Nepal
4   Rahman  22.0     Dresden         USA

In [27]:
# Lets Refill

df.fillna(df['age'].mean(), inplace=True)

In [28]:
df

name    age        city     country
0     Atul  27.00       Dhaka  Bangladesh
1    Rahim  27.75      Berlin       India
2      Ali  29.00  Chiitagong    Pakistan
3  Dahnush  33.00       Dhaka       Nepal
4   Rahman  22.00     Dresden         USA

In [30]:
data2 = {
    'name': ['Atul', 'Rahim', 'Ali'],
    'Married': [True, False, True],
}

df2 = pd.DataFrame(data2)
df2

name  Married
0   Atul     True
1  Rahim    False
2    Ali     True

In [31]:
# Lets merge data

df3 = pd.merge(df, df2, on='name')
df3

name    age        city     country  Married
0   Atul  27.00       Dhaka  Bangladesh     True
1  Rahim  27.75      Berlin       India    False
2    Ali  29.00  Chiitagong    Pakistan     True

In [33]:
import torch

import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler

In [34]:
numbers = {
    'feature1': [1,2,3,4,5, 6,7,8,9,10],
    'feature2': [10,20,30,40, 50, 60,70,80,90,100],
    'target': [1,2,3,4,5, 6,7,8,9,10]
}

df4 = pd.DataFrame(numbers)
df4

feature1  feature2  target
0         1        10       1
1         2        20       2
2         3        30       3
3         4        40       4
4         5        50       5
5         6        60       6
6         7        70       7
7         8        80       8
8         9        90       9
9        10       100      10

In [36]:
X = df4[['feature1', 'feature2']].values

In [37]:
X

array([[  1,  10],
       [  2,  20],
       [  3,  30],
       [  4,  40],
       [  5,  50],
       [  6,  60],
       [  7,  70],
       [  8,  80],
       [  9,  90],
       [ 10, 100]])

In [38]:
Y = df4['target'].values

In [39]:
Y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
scaler = StandardScaler()
X = scaler.fit_transform(X) # Data Standardization

In [41]:
scaler

StandardScaler()

In [42]:
X

array([[-1.5666989 , -1.5666989 ],
       [-1.21854359, -1.21854359],
       [-0.87038828, -0.87038828],
       [-0.52223297, -0.52223297],
       [-0.17407766, -0.17407766],
       [ 0.17407766,  0.17407766],
       [ 0.52223297,  0.52223297],
       [ 0.87038828,  0.87038828],
       [ 1.21854359,  1.21854359],
       [ 1.5666989 ,  1.5666989 ]])

In [43]:
X_tensor = torch.tensor(X, dtype=torch.float32)
Y_tensor = torch.tensor(Y, dtype=torch.float32)

In [44]:
X_tensor

tensor([[-1.5667, -1.5667],
        [-1.2185, -1.2185],
        [-0.8704, -0.8704],
        [-0.5222, -0.5222],
        [-0.1741, -0.1741],
        [ 0.1741,  0.1741],
        [ 0.5222,  0.5222],
        [ 0.8704,  0.8704],
        [ 1.2185,  1.2185],
        [ 1.5667,  1.5667]])